# -*- coding: utf-8 -*-
"""
/***************************************************************************
 getGreenObjects
                                 A QGIS plugin
 This plugin will get all the green objects in a county
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-10
        copyright            : (C) 2021 by Robin
        email                : robin-elli@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load getGreenObjects class from file getGreenObjects.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .get_green_objects import getGreenObjects
    return getGreenObjects(iface)
