# -*- coding: utf-8 -*-
"""
/***************************************************************************
 writeToCSV
                                 A QGIS plugin
 Denne utvidelsen skriver verdier fra attribut tabellen til en .CSV fil.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-17
        copyright            : (C) 2021 by Bacheloroppgave USN 2021 Erlend og Robin
        email                : bachelor@oppgave.no
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load writeToCSV class from file writeToCSV.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .skriv_til_csv import writeToCSV
    return writeToCSV(iface)
